# Generated by Django 4.1.1 on 2022-09-22 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='columns.column'),
            preserve_default=False,
        ),
    ]
