# Generated by Django 4.1.1 on 2022-09-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0002_alter_column_name'),
        ('tasks', '0002_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columns.column'),
        ),
    ]
