# Generated by Django 4.1.1 on 2022-09-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(default='New', max_length=150),
        ),
    ]
